---
- name: Site-EDGE-1
  hosts: sitea
  gather_facts: no
  become: yes
  tasks:
    - name: Adding Banner
	  ios_command: 
	    commands: 
		  - conf t
		  - banner motd *
		  - "## ANSIBLE WAS HERE ##"
		  - *
		  - end
      tags:
	    - banner
	
	- name: Assigning IP Addresses
	  ios_command:
	    commands:
		  - conf t
		  - int g3
		  - ip add 10.10.10.1 255.255.255.0
		  - no shut
		  - end
      tags:
	    - ip
    
	- name: Configuring DHCP
	  ios_command:
	    commands:
		  - conf t
		  - ip dhcp excluded-address 10.10.10.1 10.10.10.100
		  - ip dhcp pool autopool
          - network 10.10.10.0 255.255.255.0
          - default-router 10.10.10.1
          - domain-name sitea.devs 
          - dns-server 8.8.8.8
		  - end
      tags:
	    - dhcp
	
	- name: Configuring BGP
	  ios_command:
	    commands:
		  - conf t
		  - no router bgp 100
          - router bgp 100
          - bgp log-neighbor-changes
          - neighbor 192.168.102.200 remote-as 200
          - address-family ipv4
          - neighbor 192.168.102.200 activate
          - network 192.168.102.0 mask 255.255.255.0
          - end
      tags:
	    - bgp
